USE MASTER
GO
CREATE DATABASE FINANTEC ON 
( FILENAME = 'D:\SiematecBancodeDados\SIEMPRE\RISAN_TRANSPORTES\Siempre\STMBASE_data.MDF' ), 
( FILENAME = 'E:\SiematecSolucoes\RISAN_TRANSPORTES\Data\Log\STMBASE_log.ldf' ) 
FOR ATTACH