USE [master]
GO

ALTER DATABASE [DOCTORVETBASE_CCVET] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE [DOCTORVETBASE_CCVET] MODIFY NAME = [DOCTORVETBASE]
GO

ALTER DATABASE [DOCTORVETBASE] SET MULTI_USER
